all : manuelInstallation.pdf manuelUtilisation.pdf

manuelInstallation.pdf : manuelInstallation.tex
	pdflatex manuelInstallation.tex
	pdflatex manuelInstallation.tex

manuelUtilisation.pdf : manuelUtilisation.tex
	pdflatex manuelUtilisation.tex
	pdflatex manuelUtilisation.tex
